project:
  type: website

website:
  title: "MADS"
  description: "MADS - Multi-Agent Distributed System"
  site-url: "https://mads-net.github.io"
  navbar:
    left:
      - href: guides.qmd
        text: "Guides"
    right:
      - about.qmd

format:
  html:
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - flatly
      - brand
      - custom.scss
